# Culham columbus makefile
COMPILER = intel
include Makefile.$(COMPILER)
FC = mpif90
DEFAULT_LIB_LIST=$(subst :, ,$(LD_LIBRARY_PATH))
FFT_INC=-I$(subst /lib,/include,$(subst :, -I,$(LD_LIBRARY_PATH)))	# unnecessary if FPATH is set correspondingly to LD_LIBRARY_PATH
FFT_LIB=-L$(subst :, -L,$(LD_LIBRARY_PATH)) -lrfftw -lfftw
NETCDF_INC=$(FFT_INC)							# ditto
NETCDF_LIB=-lnetcdf
