#Written by S. P. Hirshman (02/26/02)
#This script converts a *.f (or *.f90) file which was generated by Windows (using Compaq Fortran) 
#to remove conditional compilation statements (converts to a file that UNIX C-preprocessor
#can precompile)

$1 !~ /^!DEC\$/ {print $0} 
$1 ~ /^!DEC\$/ {sub(/!DEC\$ /,"#"); \
gsub(/ELSEIF/,"elif"); gsub(/DEFINED/,"defined"); gsub(/UNDEFINE/,"undef"); \
gsub(/\.NOT\./,"!");   gsub(/\.AND\./,"\\&\\&"); gsub(/\.OR\./,"||"); \
gsub(/ELSE/,"else");   gsub(/ENDIF/,"endif");  gsub(/IF /,"if "); print $0}
