# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# To simulate this in Docker
# 1) Build the image: docker build --memory=1g --memory-swap=1g -t lazersos/stellopt .
# 2) Run the docker session: docker run -it --volume=/Users/slazerso/Sims_PPPL/STELLOPT:/STELLOPT --workdir="/STELLOPT" --memory=4g --memory-swap=4g --memory-swappiness=0 --entrypoint=/bin/bash lazersos/stellopt
# 3) Then execute the command below
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: lazersos/stellopt

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - echo "Test"
          - ln -Ffs SHARE/make_centos.inc make.inc
          - cd LIBSTELL
          - make clean_release
          - cd ../VMEC2000
          - make clean_release
#          - ./build_all
#          - cd LIBSTELL
#          - make shared_release
