  MODULE QSHEPMDATA  
     USE REAL_PRECISION
     REAL(KIND=R8), DIMENSION (:,:), ALLOCATABLE :: A, IW
     REAL(KIND=R8), DIMENSION(:), ALLOCATABLE :: DX, XMIN, RSQ, WS
     INTEGER, DIMENSION(:), ALLOCATABLE :: LCELL, LNEXT
 END MODULE QSHEPMDATA
