# define _NONE_ 0
# define _DEFAULT_ 1

# define _XL_ 11
# define _GFORTRAN_ 12
# define _G95_ 13
# define _NAG_ 14
# define _INTEL_ 15
# define _PGI_ 16
# define _PATHSCALE_ 17
# define _LAHEY_ 18
# define _ABSOFT_ 19
# define _ALPHA_ 20
# define _COMPAQ_ 21
# define _CRAY_ 22
# define _SUN_ 23

# define _FFTW_ 41
# define _FFTW3_ 42

# define _SPLOCAL_ 51
# define _SPNAG_ 52

# define _NAGDBLE_ 61
# define _NAGSNGL_ 62

# define _RANMT_ 71
