MODULE GIT_VERSION_MOD
   IMPLICIT NONE
#if defined(GIT_VERSION_EXT)
   CHARACTER(32), PARAMETER :: git_version = "GIT_VERSION_EXT"
   CHARACTER(40), PARAMETER :: git_hash = "GIT_HASH_EXT"
   CHARACTER(32), PARAMETER :: git_branch = "GIT_BRANCH_EXT"
   CHARACTER(19), PARAMETER :: built_on = "BUILT_ON_EXT"
#endif
END MODULE GIT_VERSION_MOD
