MODULE STELLA_STELLOPT_MOD

  LOGICAL ST_STELLOPT(10)!,ST_STELLOPT
  CHARACTER*64 ST_DKESFILE,ST_EXT
!  INTEGER KNOSOS_rad_dex
  REAL*8, ALLOCATABLE :: STELLA_Q1(:),STELLA_Q2(:)
  REAL*8 ST_Q1,ST_Q2
  
END MODULE STELLA_STELLOPT_MOD
