
  
MODULE KNOSOS_STELLOPT_MOD

  LOGICAL KN_STELLOPT(10),KNOSOS_STELLOPT
  CHARACTER*64 KN_DKESFILE,KN_EXT
  INTEGER KNOSOS_rad_dex
  REAL*8 dpsidr
  REAL*8, ALLOCATABLE :: KNOSOS_1NU(:),KNOSOS_SNU(:),KNOSOS_SBP(:),KNOSOS_FIC(:),KNOSOS_QER(:),KNOSOS_DBO(:)
!  REAL*8, ALLOCATABLE :: KNONOS_ERSHEAR(:),KNOSOS_DJRDER(:)
  REAL*8 KN_1NU,KN_SNU,KN_SBP,KN_FIC,KN_QER,KN_DBO
  
END MODULE KNOSOS_STELLOPT_MOD
