name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lazerson/stellopt-compile:latest
    env:
      MACHINE: debian
      STELLOPT_PATH: ${{ github.workspace }}
      MYHOME: ${{ github.workspace }}/bin
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    steps:
      - name: checkout sources
        uses: actions/checkout@master

      - name: set safe directory
        run: |
          git config --global --add safe.directory "${{ github.workspace }}"
          chown -R $(id -u):$(id -g) .

      - name: compile
        run: |
          cd ${STELLOPT_PATH}
          ./build_all -o clean_debug -j 2

      - name: unit_test
        run: python3 -m unittest discover -s BENCHMARKS/tests -v

      - name: test_stellopt
        run: mpiexec ./bin/xstelloptv2 test -h
