name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zhucaoxiang/stellopt:debug
    name: STELLOPT build and test
    steps:
      - name: checkout sources
        uses: actions/checkout@v2
        with: 
          path: /home/visitor
      - name: compile
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          cd /home/visitor
          ls -al
          echo ${STELLOPT_PATH}
          cd /home/visitor/STELLOPT && ./build_all 2>&1 | tee log.build
        env:
          MACHINE: docker
          STELLOPT_PATH: /home/visitor/STELLOPT