name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zhucaoxiang/stellopt:compile
    env:
      MACHINE: docker
      STELLOPT_PATH: ${{ github.workspace }}
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    steps:
      - name: checkout sources
        uses: actions/checkout@master
      - name: compile
        run: |
          # cd ${STELLOPT_PATH}
          # ./build_all --clean_debug 2>&1 | tee log.build
          cd ${STELLOPT_PATH}/VMEC2000
          make clean_debug
      - name: test
        run: |
          cd ${STELLOPT_PATH}/BENCHMARKS
          make test_vmec_QAS
